name: Template

on: push

jobs:
  job-check-template:
    runs-on: ubuntu-latest

    outputs:
      isTemplate: ${{ steps.step-check-template.outputs.isTemplate }}

    steps:
      - name: Check if template
        id: step-check-template
        run: |
          isTemplate=$(gh repo view ${{ github.repository }} --json isTemplate --jq '.isTemplate')
          echo "isTemplate=$isTemplate" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  job-materialize-template:
    runs-on: ubuntu-latest

    needs: job-check-template
    if: ${{ needs.job-check-template.outputs.isTemplate != 'true' }}

    steps:
      - name: Fetch information
        id: step-fetch-info
        uses: actions/github-script@v7
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name) {
                name
                description
                url
                owner {
                  login
                  ... on User {
                    url
                  }
                  ... on Organization {
                    url
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
            };
            const result = await github.graphql(query, variables);
            console.log(result);
            return result;

      - name: Prepare variables
        id: step-prepare-vars
        env:
          INFO: ${{ steps.step-fetch-info.outputs.result }}
        run: |
          FILTER=$(cat << EOF
          {
          name:        "\(.repository.name)",
          description: "\(.repository.description // "")",
          author:      "\(.repository.owner.login)",
          namespace:   "\(.repository.owner.url)",
          repoUrl:     "\(.repository.url)",
          repoGit:     "\(.repository.url).git",
          issuesUrl:   "\(.repository.url)/issues",
          updateUrl:   "\(.repository.url)/releases/latest/download/script.meta.js",
          downloadUrl: "\(.repository.url)/releases/latest/download/script.user.js",
          } | to_entries | map("\(.key)=\(.value)") | .[]
          EOF
          )
          echo "$INFO" | jq -c -r "$FILTER" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
